### PR TITLE
added functionality for cursoring

### PR DESCRIPTION
**Pull request by stefanjwojcik**
Hi Randy! 

I'm a newcomer to the Julia language and I thought it would interesting to contribute to this package. I've worked up a way to do cursoring such that a user can supply a screen name and a function as arguments to create a cursor object. From there, they can do `for element in cursor...` and just iterate over follower or friends lists. I also added tests to the runtests.jl file. Happy to make any changes. Thanks!

### CODE REVIEW

**Comment by randyzwitch** [comment]
Thanks @stefanjwojcik, I will check this out as soon as I can. Implementation looks reasonable from first glance :+1:

**Comment by randyzwitch** [comment]
Unfortunately, it looks like there are some dependency issues currently, irrespective of this PR. I'll submit a PR for that hopefully today, then you can pull those changes in.

After looking at this, I think it is a bit more low-level than I original expected. I think it would be more effective if the cursoring were part of the individual functions, i.e. I think it's too much to expect users to understand which functions might have cursoring (on the Twitter side), and to build their own loop. I feel like it'd be more effective if a function call had `num_tweets` parameter, and if was greater than the default then the function would keep running until it got that many tweets (within reason)

**Comment by stefanjwojcik** [comment]
Right, I see that. It sounds like a modification to the macro-generated code to add that functionality where possible would be more preferable.

**Comment by randyzwitch** [comment]
If you’re really interested in sticking around and contributing, I’m happy work in this with you. This package has been somewhat neglected, since I’m really the one person who seems to be using it over history 😂

Probably the first step is to stop generating the functions as a macro, which will make it more obvious how/where to implement the cursor

**Comment by stefanjwojcik** [comment]
Great, this would be a fun package to contribute to. I think this is an important package for Julia's ecosystem, and I don't see anything else this far along out there. I think people will use it if we do a bit of polishing. 

Right, so you think just writing out the functions similar to your blog post about macro-generating functions? I was trying to figure out if it were feasible to identify the functions where cursoring were possible and add a block do the extra functionality, but as you say it's not obvious how to do that. Perhaps the easiest way to do it is keep the macro generated for the functions that don't need cursoring, and write out the cursoring ones the old-fashioned way?

**Comment by stefanjwojcik** [comment]
Sorry my last reply was probably confusing (late night posts). I was thinking of rewriting the functions that need cursoring in the standard (non macro-generated) way, as you write in the beginning of this post: 
https://randyzwitch.com/julia-metaprogramming-refactoring/

I'd figure out which functions need cursoring functionality, write them out in standard fashion, and keep the macro-generated loop for functions that don't need that functionality.

**Comment by randyzwitch** [comment]
Yeah, I think that's a great way to approach it. Hand-write one function, while removing it from the [list of tuples](https://github.com/randyzwitch/Twitter.jl/blob/master/src/macrogenerated.jl#L1-L84), then hopefully the cursoring pattern will become obvious after you write 1 or 2 of them.

Ultimately, _somebody_ should undo all of the macros and do proper docstrings, but for now I'm happy to have one potential contributor :100:

**Comment by stefanjwojcik** [comment]
Alright, it wasn't too hard to come up with a basic cursoring pattern that works for `get_followers_ids` and `get_friends_ids`, and I'm happy to undo the macros and work on docstrings. However, before I dive in, I wanted to get your opinion on something. 

After fiddling around, it seems there are only three major types of calls: 1) calls that involve cursoring through user IDS, 2) calls that involves cursoring through tweet IDS, and 3) regular calls of the type used in `macrogenerated.jl`. Given this, and I think someone else may have suggested this, what if we went for a true macro approach? 

What if calls were of the form: `@twitter  get_followers_ids(screen_name = "stefanjwojcik", min_ids=1)`? This would involve referencing the `endpoint_tuple` file to modify the function call with the right endpoint and cursoring functionality on the fly. The functions as written would be the same, and wouldn't place much additional burden on the user. It would be a kind of middle path between undoing all the macros and what we have now. It would be substantially less code, and allow us to simply modify the `endpoint_tuple` code as the API endpoints change. 

What do you think?

**Comment by randyzwitch** [comment]
I think this sounds like a great approach. I'm certainly not married to anything in this codebase, I wrote it many years ago to learn Julia. So if you can add in cursoring like this, I think it will be a big step forward to the package

**Pull request closed without merging**
