### PR TITLE
Up OAuth compat and julia compat to make it work on the M1 mac

### LINKED ISSUE #48: Twitter.jl fails to build on M1 Mac
Posted this question here: https://stackoverflow.com/questions/72209061/how-to-install-a-julia-package-if-it-fails-to-install-build-on-an-m1-mac as well, trying to get this resolved

### PR DESCRIPTION
**Pull request by gbaraldi**
Basically the title, fixes #48

### CODE REVIEW

**Comment by logankilpatrick** [comment]
CC @randyzwitch whenever you get a chance, can you merge and tag a new release?

**Comment by randyzwitch** [comment]
Does this fix the issue here? I've been out of the Julia game for a minute, so I both haven't researched why this wasn't merged and also forgot that I submitted it 😬 

https://github.com/JuliaRegistries/General/pull/58179

**Comment by gbaraldi** [comment]
This fixes the m1 thing, the other dependencies one would have to check. But basically I would change the dataframes compat to only `1` similar to how I changed the OAuth one. It also complained about version number so I would tag something like 0.9.0 or 0.8.3 .

**Comment by randyzwitch** [comment]
Okay, I merged this and moved DataFrames to 1 like you suggested.

Here's version 0.9.0...I'd appreciate if one of you guys could watch this if it doesn't get automerged. As I mentioned, I've been away from Julia for a bit, so it's going to take me considerably longer to set up an environment, figure out the fixes, etc. than someone looking to use this package :)

https://github.com/JuliaRegistries/General/pull/60103

**Pull request merged**
